mutation buyTicket($data: tickets_insert_input!) {
  insert_tickets_one(object: $data){
    id
    price
    date
    seat_number
    movie {
      id
      title
      date
      image {
        url
      }
    }
  }
}
