query getTickets{
    tickets{
        id
        price
        seat_number
        movie{
        duration

            id
            title
            image{
                url
            }
            date
        }
        user_id
        date
    }
}