query getMovies($query: movies_bool_exp) {
  movies(where: $query) {
    date
    discrption
    duration
    id
    title
    status
    image{
      id
      url
    }
    movies_generes {
      genere {
        name
        id
      }
    }
    rating_average
  }
}
